run:
  tests: false
linters:
  enable:
    - bodyclose
    - revive
    - gosec
    - unconvert
linters-settings:
  revive:
    ignore-generated-header: true
    severity: error
    rules:
      - name: var-naming
        arguments: [["HTTP", "ASCII", "IP", "TTL", "URL", "TLS", "JSON"]]
  errcheck:
    check-type-assertions: false
    check-blank: true
  gosec:
    excludes:
      - G115
issues:
  exclude-files:
    - logging.go  # Logging has some utility functions that are useful to have around which get flagged up
    - columnar*

