// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocbcore

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockTelemetryStore creates a new instance of mockTelemetryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTelemetryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTelemetryStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockTelemetryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockTelemetryStore is an autogenerated mock type for the telemetryStore type
type mockTelemetryStore struct {
	mock.Mock
}

type mockTelemetryStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTelemetryStore) EXPECT() *mockTelemetryStore_Expecter {
	return &mockTelemetryStore_Expecter{mock: &_m.Mock}
}

// recordOperationCompletion provides a mock function for the type mockTelemetryStore
func (_mock *mockTelemetryStore) recordOperationCompletion(telemetryOutcomeMoqParam telemetryOutcome, telemetryOperationAttributesMoqParam telemetryOperationAttributes) {
	_mock.Called(telemetryOutcomeMoqParam, telemetryOperationAttributesMoqParam)
	return
}

// mockTelemetryStore_recordOperationCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'recordOperationCompletion'
type mockTelemetryStore_recordOperationCompletion_Call struct {
	*mock.Call
}

// recordOperationCompletion is a helper method to define mock.On call
//   - telemetryOutcomeMoqParam telemetryOutcome
//   - telemetryOperationAttributesMoqParam telemetryOperationAttributes
func (_e *mockTelemetryStore_Expecter) recordOperationCompletion(telemetryOutcomeMoqParam any, telemetryOperationAttributesMoqParam any) *mockTelemetryStore_recordOperationCompletion_Call {
	return &mockTelemetryStore_recordOperationCompletion_Call{Call: _e.mock.On("recordOperationCompletion", telemetryOutcomeMoqParam, telemetryOperationAttributesMoqParam)}
}

func (_c *mockTelemetryStore_recordOperationCompletion_Call) Run(run func(telemetryOutcomeMoqParam telemetryOutcome, telemetryOperationAttributesMoqParam telemetryOperationAttributes)) *mockTelemetryStore_recordOperationCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telemetryOutcome
		if args[0] != nil {
			arg0 = args[0].(telemetryOutcome)
		}
		var arg1 telemetryOperationAttributes
		if args[1] != nil {
			arg1 = args[1].(telemetryOperationAttributes)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockTelemetryStore_recordOperationCompletion_Call) Return() *mockTelemetryStore_recordOperationCompletion_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTelemetryStore_recordOperationCompletion_Call) RunAndReturn(run func(telemetryOutcomeMoqParam telemetryOutcome, telemetryOperationAttributesMoqParam telemetryOperationAttributes)) *mockTelemetryStore_recordOperationCompletion_Call {
	_c.Run(run)
	return _c
}

// recordOrphanedResponse provides a mock function for the type mockTelemetryStore
func (_mock *mockTelemetryStore) recordOrphanedResponse(telemetryOperationAttributesMoqParam telemetryOperationAttributes) {
	_mock.Called(telemetryOperationAttributesMoqParam)
	return
}

// mockTelemetryStore_recordOrphanedResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'recordOrphanedResponse'
type mockTelemetryStore_recordOrphanedResponse_Call struct {
	*mock.Call
}

// recordOrphanedResponse is a helper method to define mock.On call
//   - telemetryOperationAttributesMoqParam telemetryOperationAttributes
func (_e *mockTelemetryStore_Expecter) recordOrphanedResponse(telemetryOperationAttributesMoqParam any) *mockTelemetryStore_recordOrphanedResponse_Call {
	return &mockTelemetryStore_recordOrphanedResponse_Call{Call: _e.mock.On("recordOrphanedResponse", telemetryOperationAttributesMoqParam)}
}

func (_c *mockTelemetryStore_recordOrphanedResponse_Call) Run(run func(telemetryOperationAttributesMoqParam telemetryOperationAttributes)) *mockTelemetryStore_recordOrphanedResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telemetryOperationAttributes
		if args[0] != nil {
			arg0 = args[0].(telemetryOperationAttributes)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockTelemetryStore_recordOrphanedResponse_Call) Return() *mockTelemetryStore_recordOrphanedResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTelemetryStore_recordOrphanedResponse_Call) RunAndReturn(run func(telemetryOperationAttributesMoqParam telemetryOperationAttributes)) *mockTelemetryStore_recordOrphanedResponse_Call {
	_c.Run(run)
	return _c
}

// serialize provides a mock function for the type mockTelemetryStore
func (_mock *mockTelemetryStore) serialize() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for serialize")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockTelemetryStore_serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'serialize'
type mockTelemetryStore_serialize_Call struct {
	*mock.Call
}

// serialize is a helper method to define mock.On call
func (_e *mockTelemetryStore_Expecter) serialize() *mockTelemetryStore_serialize_Call {
	return &mockTelemetryStore_serialize_Call{Call: _e.mock.On("serialize")}
}

func (_c *mockTelemetryStore_serialize_Call) Run(run func()) *mockTelemetryStore_serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTelemetryStore_serialize_Call) Return(s string) *mockTelemetryStore_serialize_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockTelemetryStore_serialize_Call) RunAndReturn(run func() string) *mockTelemetryStore_serialize_Call {
	_c.Call.Return(run)
	return _c
}
