// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocbcore

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockDispatcher creates a new instance of mockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDispatcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockDispatcher is an autogenerated mock type for the dispatcher type
type mockDispatcher struct {
	mock.Mock
}

type mockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDispatcher) EXPECT() *mockDispatcher_Expecter {
	return &mockDispatcher_Expecter{mock: &_m.Mock}
}

// CollectionsEnabled provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) CollectionsEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectionsEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockDispatcher_CollectionsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectionsEnabled'
type mockDispatcher_CollectionsEnabled_Call struct {
	*mock.Call
}

// CollectionsEnabled is a helper method to define mock.On call
func (_e *mockDispatcher_Expecter) CollectionsEnabled() *mockDispatcher_CollectionsEnabled_Call {
	return &mockDispatcher_CollectionsEnabled_Call{Call: _e.mock.On("CollectionsEnabled")}
}

func (_c *mockDispatcher_CollectionsEnabled_Call) Run(run func()) *mockDispatcher_CollectionsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDispatcher_CollectionsEnabled_Call) Return(b bool) *mockDispatcher_CollectionsEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockDispatcher_CollectionsEnabled_Call) RunAndReturn(run func() bool) *mockDispatcher_CollectionsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchDirect provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) DispatchDirect(req *memdQRequest) (PendingOp, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DispatchDirect")
	}

	var r0 PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*memdQRequest) (PendingOp, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*memdQRequest) PendingOp); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*memdQRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDispatcher_DispatchDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchDirect'
type mockDispatcher_DispatchDirect_Call struct {
	*mock.Call
}

// DispatchDirect is a helper method to define mock.On call
//   - req *memdQRequest
func (_e *mockDispatcher_Expecter) DispatchDirect(req any) *mockDispatcher_DispatchDirect_Call {
	return &mockDispatcher_DispatchDirect_Call{Call: _e.mock.On("DispatchDirect", req)}
}

func (_c *mockDispatcher_DispatchDirect_Call) Run(run func(req *memdQRequest)) *mockDispatcher_DispatchDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *memdQRequest
		if args[0] != nil {
			arg0 = args[0].(*memdQRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockDispatcher_DispatchDirect_Call) Return(pendingOp PendingOp, err error) *mockDispatcher_DispatchDirect_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockDispatcher_DispatchDirect_Call) RunAndReturn(run func(req *memdQRequest) (PendingOp, error)) *mockDispatcher_DispatchDirect_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchDirectToAddress provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) DispatchDirectToAddress(req *memdQRequest, address string) (PendingOp, error) {
	ret := _mock.Called(req, address)

	if len(ret) == 0 {
		panic("no return value specified for DispatchDirectToAddress")
	}

	var r0 PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*memdQRequest, string) (PendingOp, error)); ok {
		return returnFunc(req, address)
	}
	if returnFunc, ok := ret.Get(0).(func(*memdQRequest, string) PendingOp); ok {
		r0 = returnFunc(req, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*memdQRequest, string) error); ok {
		r1 = returnFunc(req, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDispatcher_DispatchDirectToAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchDirectToAddress'
type mockDispatcher_DispatchDirectToAddress_Call struct {
	*mock.Call
}

// DispatchDirectToAddress is a helper method to define mock.On call
//   - req *memdQRequest
//   - address string
func (_e *mockDispatcher_Expecter) DispatchDirectToAddress(req any, address any) *mockDispatcher_DispatchDirectToAddress_Call {
	return &mockDispatcher_DispatchDirectToAddress_Call{Call: _e.mock.On("DispatchDirectToAddress", req, address)}
}

func (_c *mockDispatcher_DispatchDirectToAddress_Call) Run(run func(req *memdQRequest, address string)) *mockDispatcher_DispatchDirectToAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *memdQRequest
		if args[0] != nil {
			arg0 = args[0].(*memdQRequest)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDispatcher_DispatchDirectToAddress_Call) Return(pendingOp PendingOp, err error) *mockDispatcher_DispatchDirectToAddress_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockDispatcher_DispatchDirectToAddress_Call) RunAndReturn(run func(req *memdQRequest, address string) (PendingOp, error)) *mockDispatcher_DispatchDirectToAddress_Call {
	_c.Call.Return(run)
	return _c
}

// PipelineSnapshot provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) PipelineSnapshot() (*pipelineSnapshot, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PipelineSnapshot")
	}

	var r0 *pipelineSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*pipelineSnapshot, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *pipelineSnapshot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pipelineSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDispatcher_PipelineSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PipelineSnapshot'
type mockDispatcher_PipelineSnapshot_Call struct {
	*mock.Call
}

// PipelineSnapshot is a helper method to define mock.On call
func (_e *mockDispatcher_Expecter) PipelineSnapshot() *mockDispatcher_PipelineSnapshot_Call {
	return &mockDispatcher_PipelineSnapshot_Call{Call: _e.mock.On("PipelineSnapshot")}
}

func (_c *mockDispatcher_PipelineSnapshot_Call) Run(run func()) *mockDispatcher_PipelineSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDispatcher_PipelineSnapshot_Call) Return(pipelineSnapshotMoqParam *pipelineSnapshot, err error) *mockDispatcher_PipelineSnapshot_Call {
	_c.Call.Return(pipelineSnapshotMoqParam, err)
	return _c
}

func (_c *mockDispatcher_PipelineSnapshot_Call) RunAndReturn(run func() (*pipelineSnapshot, error)) *mockDispatcher_PipelineSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// RequeueDirect provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) RequeueDirect(req *memdQRequest, isRetry bool) {
	_mock.Called(req, isRetry)
	return
}

// mockDispatcher_RequeueDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequeueDirect'
type mockDispatcher_RequeueDirect_Call struct {
	*mock.Call
}

// RequeueDirect is a helper method to define mock.On call
//   - req *memdQRequest
//   - isRetry bool
func (_e *mockDispatcher_Expecter) RequeueDirect(req any, isRetry any) *mockDispatcher_RequeueDirect_Call {
	return &mockDispatcher_RequeueDirect_Call{Call: _e.mock.On("RequeueDirect", req, isRetry)}
}

func (_c *mockDispatcher_RequeueDirect_Call) Run(run func(req *memdQRequest, isRetry bool)) *mockDispatcher_RequeueDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *memdQRequest
		if args[0] != nil {
			arg0 = args[0].(*memdQRequest)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDispatcher_RequeueDirect_Call) Return() *mockDispatcher_RequeueDirect_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockDispatcher_RequeueDirect_Call) RunAndReturn(run func(req *memdQRequest, isRetry bool)) *mockDispatcher_RequeueDirect_Call {
	_c.Run(run)
	return _c
}

// SetPostCompleteErrorHandler provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) SetPostCompleteErrorHandler(handler postCompleteErrorHandler) {
	_mock.Called(handler)
	return
}

// mockDispatcher_SetPostCompleteErrorHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPostCompleteErrorHandler'
type mockDispatcher_SetPostCompleteErrorHandler_Call struct {
	*mock.Call
}

// SetPostCompleteErrorHandler is a helper method to define mock.On call
//   - handler postCompleteErrorHandler
func (_e *mockDispatcher_Expecter) SetPostCompleteErrorHandler(handler any) *mockDispatcher_SetPostCompleteErrorHandler_Call {
	return &mockDispatcher_SetPostCompleteErrorHandler_Call{Call: _e.mock.On("SetPostCompleteErrorHandler", handler)}
}

func (_c *mockDispatcher_SetPostCompleteErrorHandler_Call) Run(run func(handler postCompleteErrorHandler)) *mockDispatcher_SetPostCompleteErrorHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 postCompleteErrorHandler
		if args[0] != nil {
			arg0 = args[0].(postCompleteErrorHandler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockDispatcher_SetPostCompleteErrorHandler_Call) Return() *mockDispatcher_SetPostCompleteErrorHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockDispatcher_SetPostCompleteErrorHandler_Call) RunAndReturn(run func(handler postCompleteErrorHandler)) *mockDispatcher_SetPostCompleteErrorHandler_Call {
	_c.Run(run)
	return _c
}

// SupportsCollections provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) SupportsCollections() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsCollections")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockDispatcher_SupportsCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsCollections'
type mockDispatcher_SupportsCollections_Call struct {
	*mock.Call
}

// SupportsCollections is a helper method to define mock.On call
func (_e *mockDispatcher_Expecter) SupportsCollections() *mockDispatcher_SupportsCollections_Call {
	return &mockDispatcher_SupportsCollections_Call{Call: _e.mock.On("SupportsCollections")}
}

func (_c *mockDispatcher_SupportsCollections_Call) Run(run func()) *mockDispatcher_SupportsCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDispatcher_SupportsCollections_Call) Return(b bool) *mockDispatcher_SupportsCollections_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockDispatcher_SupportsCollections_Call) RunAndReturn(run func() bool) *mockDispatcher_SupportsCollections_Call {
	_c.Call.Return(run)
	return _c
}
