// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocbcore

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockConfigManager creates a new instance of mockConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockConfigManager is an autogenerated mock type for the configManager type
type mockConfigManager struct {
	mock.Mock
}

type mockConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigManager) EXPECT() *mockConfigManager_Expecter {
	return &mockConfigManager_Expecter{mock: &_m.Mock}
}

// AddConfigWatcher provides a mock function for the type mockConfigManager
func (_mock *mockConfigManager) AddConfigWatcher(watcher routeConfigWatcher) {
	_mock.Called(watcher)
	return
}

// mockConfigManager_AddConfigWatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConfigWatcher'
type mockConfigManager_AddConfigWatcher_Call struct {
	*mock.Call
}

// AddConfigWatcher is a helper method to define mock.On call
//   - watcher routeConfigWatcher
func (_e *mockConfigManager_Expecter) AddConfigWatcher(watcher any) *mockConfigManager_AddConfigWatcher_Call {
	return &mockConfigManager_AddConfigWatcher_Call{Call: _e.mock.On("AddConfigWatcher", watcher)}
}

func (_c *mockConfigManager_AddConfigWatcher_Call) Run(run func(watcher routeConfigWatcher)) *mockConfigManager_AddConfigWatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 routeConfigWatcher
		if args[0] != nil {
			arg0 = args[0].(routeConfigWatcher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConfigManager_AddConfigWatcher_Call) Return() *mockConfigManager_AddConfigWatcher_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConfigManager_AddConfigWatcher_Call) RunAndReturn(run func(watcher routeConfigWatcher)) *mockConfigManager_AddConfigWatcher_Call {
	_c.Run(run)
	return _c
}

// RemoveConfigWatcher provides a mock function for the type mockConfigManager
func (_mock *mockConfigManager) RemoveConfigWatcher(watcher routeConfigWatcher) {
	_mock.Called(watcher)
	return
}

// mockConfigManager_RemoveConfigWatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveConfigWatcher'
type mockConfigManager_RemoveConfigWatcher_Call struct {
	*mock.Call
}

// RemoveConfigWatcher is a helper method to define mock.On call
//   - watcher routeConfigWatcher
func (_e *mockConfigManager_Expecter) RemoveConfigWatcher(watcher any) *mockConfigManager_RemoveConfigWatcher_Call {
	return &mockConfigManager_RemoveConfigWatcher_Call{Call: _e.mock.On("RemoveConfigWatcher", watcher)}
}

func (_c *mockConfigManager_RemoveConfigWatcher_Call) Run(run func(watcher routeConfigWatcher)) *mockConfigManager_RemoveConfigWatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 routeConfigWatcher
		if args[0] != nil {
			arg0 = args[0].(routeConfigWatcher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConfigManager_RemoveConfigWatcher_Call) Return() *mockConfigManager_RemoveConfigWatcher_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConfigManager_RemoveConfigWatcher_Call) RunAndReturn(run func(watcher routeConfigWatcher)) *mockConfigManager_RemoveConfigWatcher_Call {
	_c.Run(run)
	return _c
}
