// Code generated by mockery v2.52.2. DO NOT EDIT.

package gocbcore

import mock "github.com/stretchr/testify/mock"

// mockTelemetryStore is an autogenerated mock type for the telemetryStore type
type mockTelemetryStore struct {
	mock.Mock
}

// recordOp provides a mock function with given fields: _a0
func (_m *mockTelemetryStore) recordOp(_a0 telemetryOperationAttributes) {
	_m.Called(_a0)
}

// serialize provides a mock function with no fields
func (_m *mockTelemetryStore) serialize() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for serialize")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// newMockTelemetryStore creates a new instance of mockTelemetryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTelemetryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTelemetryStore {
	mock := &mockTelemetryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
