// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocbcore

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockHttpComponentInterface creates a new instance of mockHttpComponentInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHttpComponentInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHttpComponentInterface {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockHttpComponentInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockHttpComponentInterface is an autogenerated mock type for the httpComponentInterface type
type mockHttpComponentInterface struct {
	mock.Mock
}

type mockHttpComponentInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHttpComponentInterface) EXPECT() *mockHttpComponentInterface_Expecter {
	return &mockHttpComponentInterface_Expecter{mock: &_m.Mock}
}

// DoInternalHTTPRequest provides a mock function for the type mockHttpComponentInterface
func (_mock *mockHttpComponentInterface) DoInternalHTTPRequest(req *httpRequest, skipConfigCheck bool) (*HTTPResponse, error) {
	ret := _mock.Called(req, skipConfigCheck)

	if len(ret) == 0 {
		panic("no return value specified for DoInternalHTTPRequest")
	}

	var r0 *HTTPResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*httpRequest, bool) (*HTTPResponse, error)); ok {
		return returnFunc(req, skipConfigCheck)
	}
	if returnFunc, ok := ret.Get(0).(func(*httpRequest, bool) *HTTPResponse); ok {
		r0 = returnFunc(req, skipConfigCheck)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*HTTPResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*httpRequest, bool) error); ok {
		r1 = returnFunc(req, skipConfigCheck)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockHttpComponentInterface_DoInternalHTTPRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoInternalHTTPRequest'
type mockHttpComponentInterface_DoInternalHTTPRequest_Call struct {
	*mock.Call
}

// DoInternalHTTPRequest is a helper method to define mock.On call
//   - req *httpRequest
//   - skipConfigCheck bool
func (_e *mockHttpComponentInterface_Expecter) DoInternalHTTPRequest(req any, skipConfigCheck any) *mockHttpComponentInterface_DoInternalHTTPRequest_Call {
	return &mockHttpComponentInterface_DoInternalHTTPRequest_Call{Call: _e.mock.On("DoInternalHTTPRequest", req, skipConfigCheck)}
}

func (_c *mockHttpComponentInterface_DoInternalHTTPRequest_Call) Run(run func(req *httpRequest, skipConfigCheck bool)) *mockHttpComponentInterface_DoInternalHTTPRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *httpRequest
		if args[0] != nil {
			arg0 = args[0].(*httpRequest)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockHttpComponentInterface_DoInternalHTTPRequest_Call) Return(hTTPResponse *HTTPResponse, err error) *mockHttpComponentInterface_DoInternalHTTPRequest_Call {
	_c.Call.Return(hTTPResponse, err)
	return _c
}

func (_c *mockHttpComponentInterface_DoInternalHTTPRequest_Call) RunAndReturn(run func(req *httpRequest, skipConfigCheck bool) (*HTTPResponse, error)) *mockHttpComponentInterface_DoInternalHTTPRequest_Call {
	_c.Call.Return(run)
	return _c
}
